import { DealerBrand, DealerLocation, DealerStatus } from "../../enums/dealer.enum";

export interface DealerUpdate {
    _id: string;
    dealerStatus?: DealerStatus;
    dealerTitle?: string;
    dealerBrand?: DealerBrand;
    dealerPassword?: string;
    dealerLocation?: DealerLocation;
    dealerAddress?: string;
    dealerImage?: string;
    dealerImages?: string;
    dealerPhone?: string;
    dealerPhone2?: string;
    dealerEmail?: string;
    dealerKakaoTalk?: string;
    dealerYoutube?: string;
    dealerInstagram?: string;
    dealerFacebook?: string;
    dealerTikTok?: string;
    dealerNaverBlog?: string;
    dealerXcom?: string;
    dealerShortDesc?: string;
    dealerLongDesc?: string;
    dealerOpenAt?: string;
    dealerCloseAt?: string;
    dealerOpenSunday?: string;
    dealerCloseSunday?: string;
    dealerOpenSaturday?: string;
    dealerCloseSaturday?: string;
    dealerPublicHolidays?: boolean;
    dealerFinancing?: boolean;
    dealerCarService?: boolean;
    dealerTradeIn?: boolean;
    dealerCustomization?: boolean;
    dealerWarranties?: boolean;
    dealerParts?: boolean;
    dealerAccessories?: boolean;
    dealerCarDetailing?: boolean;
    dealerCarWash?: boolean;
    dealerCarTestDrive?: boolean;
    dealerCarDelivery?: boolean;
    dealerPlusService?: string;
}